export const clerkAppearance = {
  variables: {
    colorPrimary: "#8b5cf6",
    borderRadius: "0.75rem",
  },
  elements: {
    card: "!bg-white/90 dark:!bg-[#070a12]/90 !border !border-black/10 dark:!border-white/10 !shadow-2xl shadow-purple-500/10 dark:!shadow-black/40 backdrop-blur-2xl",
    rootBox: "!w-full",
    headerTitle: "!text-black dark:!text-white !font-semibold",
    headerSubtitle: "!text-black/70 dark:!text-white/70",
    socialButtonsBlockButton: "!border-black/10 dark:!border-white/10 !bg-black/5 dark:!bg-white/5 !text-black dark:!text-white hover:!bg-black/10 dark:hover:!bg-white/10 !shadow-none",
    socialButtonsBlockButtonText: "!text-black dark:!text-white !font-medium",
    dividerLine: "!bg-black/10 dark:!bg-white/10",
    dividerText: "!text-black/45 dark:!text-white/45",
    formFieldLabel: "!text-black/75 dark:!text-white/75",
    formFieldInput: "!bg-black/5 dark:!bg-white/10 !border-black/15 dark:!border-white/15 !text-black dark:!text-white placeholder:!text-black/40 dark:placeholder:!text-white/40 focus:!ring-2 focus:!ring-purple-500/40",
    formButtonPrimary: "!bg-gradient-to-r !from-blue-600 !to-purple-600 hover:!from-blue-500 hover:!to-purple-500 !text-white !shadow-lg !shadow-purple-500/25",
    footer: "!bg-transparent",
    footerAction: "!bg-transparent",
    footerActionText: "!text-black/60 dark:!text-white/60",
    footerActionLink: "!text-purple-600 dark:!text-purple-300 hover:!text-purple-500 dark:hover:!text-purple-200",
    identityPreview: "!bg-black/5 dark:!bg-white/5 !border-black/10 dark:!border-white/10",
    identityPreviewText: "!text-black dark:!text-white",
    identityPreviewEditButton: "!text-purple-600 dark:!text-purple-300",
    userButtonPopoverCard: "!bg-white/95 dark:!bg-[#070a12]/95 !border !border-black/10 dark:!border-white/10 !shadow-2xl shadow-purple-500/10 dark:!shadow-black/40 backdrop-blur-2xl",
    userButtonPopoverMain: "!bg-transparent",
    userButtonPopoverFooter: "!bg-black/[0.03] dark:!bg-white/[0.03]",
    userPreviewMainIdentifier: "!text-black dark:!text-white",
    userPreviewSecondaryIdentifier: "!text-black/55 dark:!text-white/55",
    userButtonPopoverActionButton: "!text-black/75 dark:!text-white/75 hover:!bg-black/5 dark:hover:!bg-white/10 hover:!text-black dark:hover:!text-white",
    userButtonPopoverActionButtonText: "!text-black/75 dark:!text-white/75",
    userButtonPopoverActionButtonIcon: "!text-black/60 dark:!text-white/60",
  },
} as const;

export const clerkUserProfileAppearance = {
  elements: {
    card: "!bg-white dark:!bg-[#070a12] !border !border-black/10 dark:!border-white/10 !shadow-2xl !rounded-[2px]",
    navbar: "!bg-black/[0.02] dark:!bg-black/20 !border-r !border-black/10 dark:!border-white/10 !rounded-l-[2px]",
    navbarButton: "!text-black/60 dark:!text-white/60 !font-medium hover:!bg-black/5 dark:hover:!bg-white/5",
    navbarButton__active: "!text-purple-600 dark:!text-purple-400 !bg-purple-500/10",
    pageScrollBox: "!bg-transparent",
    page: "!bg-transparent",
    headerTitle: "!text-black dark:!text-white !font-bold",
    headerSubtitle: "!text-black/60 dark:!text-white/60",
    profileSectionTitle: "!text-black/80 dark:!text-white/80 !font-mono !text-[11px] !uppercase !tracking-widest !border-b !border-black/10 dark:!border-white/10 !pb-2",
    profileSectionContent: "!text-black/70 dark:!text-white/70",
    formFieldLabel: "!text-black/60 dark:!text-white/60 !font-mono !text-[10px] !uppercase !tracking-wider",
    formFieldInput: "!bg-black/[0.03] dark:!bg-white/5 !border-black/10 dark:!border-white/10 !text-black dark:!text-white !rounded-[2px] focus:!ring-2 focus:!ring-purple-500/30",
    formButtonPrimary: "!bg-purple-600 hover:!bg-purple-500 !text-white !rounded-[2px] !shadow-lg !shadow-purple-500/20",
    formButtonReset: "!text-black/60 dark:!text-white/60 hover:!text-black dark:hover:!text-white",
    badge: "!bg-purple-500/10 !text-purple-600 dark:!text-purple-400 !font-mono !text-[10px] !rounded-[2px] !border !border-purple-500/20",
    avatarBox: "!rounded-[2px] !border-2 !border-black/10 dark:!border-white/10",
    identityPreviewText: "!text-black dark:!text-white",
    identityPreviewEditButton: "!text-purple-600 dark:!text-purple-400",
    dividerLine: "!bg-black/10 dark:!bg-white/10",
    dividerText: "!text-black/40 dark:!text-white/40 !font-mono !text-[11px]",
    accordionTriggerButton: "!text-black dark:!text-white hover:!bg-black/5 dark:hover:!bg-white/5",
    // Fix for the specific background inconsistency in dark mode
    activeDeviceIcon: "!text-purple-600 dark:!text-purple-400",
    breadcrumbsItem: "!text-black/60 dark:!text-white/60",
    breadcrumbsItem__active: "!text-black dark:!text-white",
    scrollBox: "!bg-transparent",
    footer: "!hidden",
    footerAction: "!hidden",
    // Additional fixes for account switching and internal modals
    modalBackdrop: "!bg-black/80",
    modalCloseButton: "!text-white/60 hover:!text-white",
    modalContent: "!bg-[#070a12] !border !border-white/10 !rounded-[2px]",
  },
} as any;
