export const clerkAppearance = {
  variables: {
    colorPrimary: "#8b5cf6",
    borderRadius: "0.75rem",
  },
  elements: {
    card: "!bg-white/90 dark:!bg-[#070a12]/90 !border !border-black/10 dark:!border-white/10 !shadow-2xl shadow-purple-500/10 dark:!shadow-black/40 backdrop-blur-2xl",
    rootBox: "!w-full",
    headerTitle: "!text-black dark:!text-white !font-semibold",
    headerSubtitle: "!text-black/70 dark:!text-white/70",
    socialButtonsBlockButton: "!border-black/10 dark:!border-white/10 !bg-black/5 dark:!bg-white/5 !text-black dark:!text-white hover:!bg-black/10 dark:hover:!bg-white/10 !shadow-none",
    socialButtonsBlockButtonText: "!text-black dark:!text-white !font-medium",
    dividerLine: "!bg-black/10 dark:!bg-white/10",
    dividerText: "!text-black/45 dark:!text-white/45",
    formFieldLabel: "!text-black/75 dark:!text-white/75",
    formFieldInput: "!bg-black/5 dark:!bg-white/10 !border-black/15 dark:!border-white/15 !text-black dark:!text-white placeholder:!text-black/40 dark:placeholder:!text-white/40 focus:!ring-2 focus:!ring-purple-500/40",
    formButtonPrimary: "!bg-gradient-to-r !from-blue-600 !to-purple-600 hover:!from-blue-500 hover:!to-purple-500 !text-white !shadow-lg !shadow-purple-500/25",
    footer: "!bg-transparent",
    footerAction: "!bg-transparent",
    footerActionText: "!text-black/60 dark:!text-white/60",
    footerActionLink: "!text-purple-600 dark:!text-purple-300 hover:!text-purple-500 dark:hover:!text-purple-200",
    identityPreview: "!bg-black/5 dark:!bg-white/5 !border-black/10 dark:!border-white/10",
    identityPreviewText: "!text-black dark:!text-white",
    identityPreviewEditButton: "!text-purple-600 dark:!text-purple-300",
    userButtonPopoverCard: "!bg-white/95 dark:!bg-[#070a12]/95 !border !border-black/10 dark:!border-white/10 !shadow-2xl shadow-purple-500/10 dark:!shadow-black/40 backdrop-blur-2xl",
    userButtonPopoverMain: "!bg-transparent",
    userButtonPopoverFooter: "!bg-black/[0.03] dark:!bg-white/[0.03]",
    userPreviewMainIdentifier: "!text-black dark:!text-white",
    userPreviewSecondaryIdentifier: "!text-black/55 dark:!text-white/55",
    userButtonPopoverActionButton: "!text-black/75 dark:!text-white/75 hover:!bg-black/5 dark:hover:!bg-white/10 hover:!text-black dark:hover:!text-white",
    userButtonPopoverActionButtonText: "!text-black/75 dark:!text-white/75",
    userButtonPopoverActionButtonIcon: "!text-black/60 dark:!text-white/60",
  },
} as const;

export const clerkUserProfileAppearance = {
  variables: {
    colorPrimary: "#8b5cf6",
    borderRadius: "0.75rem",
    colorDanger: "#ef4444",
  },
  elements: {
    rootBox: "!w-full",
    card: "!bg-white dark:!bg-[#0b1020] !border !border-black/10 dark:!border-white/10 !shadow-none backdrop-blur-2xl",
    navbar: "!bg-slate-50 dark:!bg-[#090d1a] !border-black/10 dark:!border-white/10",
    navbarButton: "!text-black/70 dark:!text-white/70 hover:!bg-black/5 dark:hover:!bg-white/10 hover:!text-black dark:hover:!text-white data-[active=true]:!bg-black/5 dark:data-[active=true]:!bg-white/10 data-[active=true]:!text-purple-600 dark:data-[active=true]:!text-purple-300",
    navbarButtonIcon: "!text-black/60 dark:!text-white/60",
    navbarButtonText: "!text-black/70 dark:!text-white/70",
    pageScrollBox: "!bg-transparent",
    page: "!bg-transparent",
    headerTitle: "!text-black dark:!text-white",
    headerSubtitle: "!text-black/65 dark:!text-white/65",
    profileSectionTitle: "!text-black dark:!text-white",
    profileSectionTitleText: "!text-black dark:!text-white",
    profileSectionPrimaryButton: "!text-purple-600 dark:!text-purple-300 hover:!text-purple-500 dark:hover:!text-purple-200",
    profileSectionItem: "!border-black/10 dark:!border-white/10",
    profileSectionItemLabel: "!text-black/55 dark:!text-white/55",
    profileSectionItemValue: "!text-black/85 dark:!text-white/85",
    profileSectionItemList: "!border-black/10 dark:!border-white/10",
    badge: "!bg-black/10 dark:!bg-white/10 !text-black/70 dark:!text-white/70",
    accordionTriggerButton: "!text-black dark:!text-white",
    accordionContent: "!text-black/75 dark:!text-white/75",
    menuButton: "!text-black/60 dark:!text-white/60 hover:!bg-black/5 dark:hover:!bg-white/10",
    menuList: "!bg-white dark:!bg-[#0b1020] !border-black/10 dark:!border-white/10",
    menuItem: "!text-black/75 dark:!text-white/75 hover:!bg-black/5 dark:hover:!bg-white/10 hover:!text-black dark:hover:!text-white",
    modalContent: "!bg-white dark:!bg-[#0b1020] !text-black dark:!text-white",
    modalCloseButton: "!text-black/50 dark:!text-white/50 hover:!text-black dark:hover:!text-white",
    formFieldLabel: "!text-black/70 dark:!text-white/70",
    formFieldInput: "!bg-black/5 dark:!bg-white/10 !border-black/15 dark:!border-white/15 !text-black dark:!text-white",
    formButtonPrimary: "!bg-gradient-to-r !from-blue-600 !to-purple-600 hover:!from-blue-500 hover:!to-purple-500 !text-white",
    formFieldSuccessText: "!text-green-600 dark:!text-green-300",
    formFieldErrorText: "!text-red-600 dark:!text-red-300",
  },
} as const;
